### ISSUE TITLE
Social Icons

### ISSUE THREAD

**Issue by fedyk** [liku/solidolbarbers.com#1]
Use SVG for socials icons to better look on high dpi screen.

**Comment by liku** [comment]
+1

**Comment by fedyk** [comment]
Before: https://api.monosnap.com/rpc/file/download?id=mw1uNXIsthBrj08NoUOFxSGkEOKper
After: https://api.monosnap.com/rpc/file/download?id=bdElNJxAhX4U4vb8yiqnGUinxgIMb8
